import { useEffect } from 'react';

const sameLeftRailApi = (previous, next) => {
  if (!previous) return false;
  const keys = Object.keys(next);
  if (keys.length !== Object.keys(previous).length) return false;
  return keys.every((key) => {
    const previousValue = previous[key];
    const nextValue = next[key];
    if (typeof previousValue === 'function' && typeof nextValue === 'function') {
      return true;
    }
    return previousValue === nextValue;
  });
};

export function usePdfLeftRailApiPublisher({
  isActive,
  onLeftRailApiChange,
  pdfSidebarRef,
  features,
  pdfDoc,
  pdfSearchDocumentKey,
  numPages,
  pageNum,
  goToPage,
  navigateToMatch,
  handleFindTextMatches,
  handleClearTextSearch,
  searchResults,
  currentMatchIndex,
  handleSearchResultsChange,
  handleCurrentMatchIndexChange,
  handleDuplicatePage,
  handleDeletePage,
  handleCutPage,
  handleCopyPage,
  handlePastePage,
  clipboardPage,
  clipboardType,
  handleRotatePage,
  handleMirrorPage,
  handleResetPage,
  handleReorderPages,
  pageTransformations,
  printPanelGetThumbnail,
  bookmarks,
  handleBookmarkCreate,
  handleBookmarkUpdate,
  handleBookmarkDelete,
  spaces,
  handleSpaceCreate,
  handleSpaceUpdate,
  handleSpaceDelete,
  activeSpaceId,
  handleSetActiveSpace,
  handleExitSpaceMode,
  handleRequestRegionEdit,
  handleCancelRegionEdit,
  handleSpaceAssignPages,
  handleSpaceRenamePage,
  handleSpaceRemovePage,
  handleReorderSpaces,
  handleExportSpaceToCSV,
  handleExportSpaceToPDF,
  showRegionSelection,
  shouldShowPage,
  activeSpacePages,
  scale,
  tabId,
  onPageDrop,
  getCanvasAnnotationVisibilityState,
  handleToggleCanvasAnnotations,
  getSurveyAnnotationVisibilityState,
  handleToggleSurveyAnnotations,
  selectedSpaceId,
  handleToggleRegionOverlay,
  isRegionOverlayEnabled,
  isRegionOverlayToggleEnabled,
  showSurveyPanel,
  selectedModuleId,
  cloudSyncStatus,
  cloudSyncQueueSize,
  cloudSyncEnabled,
  cloudSyncForceFlush,
  documentPresenceList,
  currentDocumentId,
  user,
  handleLeftRailToggleCollapse,
  handleRestoreHistoryActivity
}) {
  useEffect(() => {
    if (!isActive || typeof onLeftRailApiChange !== 'function') return;

    const nextLeftRailApi = {
      ref: pdfSidebarRef,
      features,
      pdfDoc,
      pdfDocumentKey: pdfSearchDocumentKey,
      numPages,
      pageNum,
      onNavigateToPage: goToPage,
      onNavigateToMatch: navigateToMatch,
      onFindTextMatches: handleFindTextMatches,
      onClearTextSearch: handleClearTextSearch,
      searchResults,
      currentMatchIndex,
      onSearchResultsChange: handleSearchResultsChange,
      onCurrentMatchIndexChange: handleCurrentMatchIndexChange,
      onDuplicatePage: handleDuplicatePage,
      onDeletePage: handleDeletePage,
      onCutPage: handleCutPage,
      onCopyPage: handleCopyPage,
      onPastePage: handlePastePage,
      clipboardPage,
      clipboardType,
      onRotatePage: handleRotatePage,
      onMirrorPage: handleMirrorPage,
      onResetPage: handleResetPage,
      onReorderPages: handleReorderPages,
      pageTransformations,
      getThumbnail: printPanelGetThumbnail,
      bookmarks,
      onBookmarkCreate: handleBookmarkCreate,
      onBookmarkUpdate: handleBookmarkUpdate,
      onBookmarkDelete: handleBookmarkDelete,
      spaces,
      onSpaceCreate: handleSpaceCreate,
      onSpaceUpdate: handleSpaceUpdate,
      onSpaceDelete: handleSpaceDelete,
      activeSpaceId,
      onSetActiveSpace: handleSetActiveSpace,
      onExitSpaceMode: handleExitSpaceMode,
      onRequestRegionEdit: handleRequestRegionEdit,
      onCancelRegionEdit: handleCancelRegionEdit,
      onSpaceAssignPages: handleSpaceAssignPages,
      onSpaceRenamePage: handleSpaceRenamePage,
      onSpaceRemovePage: handleSpaceRemovePage,
      onReorderSpaces: handleReorderSpaces,
      onExportSpaceCSV: handleExportSpaceToCSV,
      onExportSpacePDF: handleExportSpaceToPDF,
      isRegionSelectionActive: showRegionSelection,
      shouldShowPage,
      activeSpacePages,
      scale,
      tabId,
      onPageDrop,
      getCanvasAnnotationVisibilityState,
      onToggleCanvasAnnotations: handleToggleCanvasAnnotations,
      getSurveyAnnotationVisibilityState,
      onToggleSurveyAnnotations: handleToggleSurveyAnnotations,
      selectedSpaceId,
      onToggleRegionOverlay: handleToggleRegionOverlay,
      getRegionOverlayEnabled: isRegionOverlayEnabled,
      isRegionOverlayToggleEnabled,
      showSurveyPanel,
      selectedModuleId,
      cloudSyncStatus,
      cloudSyncQueueSize,
      cloudSyncEnabled,
      cloudSyncOnRetry: cloudSyncForceFlush,
      presence: documentPresenceList,
      currentUserId: user?.id || null,
      currentUserEmail: user?.email || null,
      currentUserDisplayName: user?.user_metadata?.full_name || null,
      onToggleCollapse: handleLeftRailToggleCollapse,
      documentId: currentDocumentId,
      user,
      onRestoreHistoryActivity: handleRestoreHistoryActivity
    };

    onLeftRailApiChange((previous) => (
      sameLeftRailApi(previous, nextLeftRailApi) ? previous : nextLeftRailApi
    ));
  });
}
