import { StyleSheet } from 'react-native';
import { colors } from './constants';
import { CHECKLIST_ITEM_GAP, CHECKLIST_ITEM_HEIGHT } from './utils/pageUtils';

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  topBar: {
    paddingHorizontal: 0,
    backgroundColor: colors.chrome,
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 90,
  },
  topLeftGroup: {
    position: 'absolute',
    left: 7,
    bottom: 4,
    maxWidth: 172,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  topCenterGroup: {
    position: 'absolute',
    left: '50%',
    bottom: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    transform: [{ translateX: -34 }],
    zIndex: 95,
  },
  topIcon: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBackButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titlePill: {
    height: 25,
    maxWidth: 136,
    paddingHorizontal: 12,
    borderRadius: 5,
    backgroundColor: '#2A2B31',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  titleText: {
    color: colors.text,
    fontWeight: '700',
    fontSize: 13,
  },
  topActions: {
    position: 'absolute',
    right: 9,
    bottom: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  subBar: {
    backgroundColor: '#202126',
    borderBottomWidth: 1,
    borderBottomColor: '#090A0D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    position: 'relative',
    zIndex: 70,
  },
  historyTools: {
    position: 'absolute',
    right: 8,
    bottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    zIndex: 96,
  },
  historyButton: {
    width: 26,
    height: 26,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  historyButtonDisabled: {
    opacity: 0.56,
  },
  pageZoomTools: {
    position: 'relative',
    width: 68,
    alignItems: 'center',
    zIndex: 80,
  },
  pageZoomButton: {
    height: 24,
    width: 68,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#343B46',
    backgroundColor: '#171A20',
    paddingHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  pageZoomButtonActive: {
    borderColor: '#2B6FB6',
    backgroundColor: '#121B2A',
  },
  pageZoomText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  pageZoomInput: {
    width: 16,
    height: 20,
    padding: 0,
    color: colors.text,
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  pageZoomMenu: {
    position: 'absolute',
    top: 29,
    left: -35,
    width: 138,
    borderRadius: 8,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: '#3A4250',
    padding: 5,
    gap: 3,
  },
  pageZoomMenuItem: {
    height: 30,
    borderRadius: 6,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pageZoomMenuItemActive: {
    backgroundColor: '#132135',
  },
  pageZoomMenuText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  pageZoomMenuTextActive: {
    color: colors.blue,
  },
  annotationFormatLayer: {
    position: 'absolute',
    right: 0,
    zIndex: 58,
  },
  annotationFormatBar: {
    height: 36,
    backgroundColor: '#202126',
    borderBottomWidth: 1,
    borderBottomColor: '#090A0D',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  annotationFormatCenter: {
    width: '100%',
    height: 36,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  formatKeepActiveButton: {
    height: 30,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#3F4652',
    backgroundColor: '#2A2D34',
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  formatKeepActiveButtonActive: {
    borderColor: '#2B6FB6',
    backgroundColor: '#132235',
  },
  formatKeepActiveBox: {
    width: 14,
    height: 14,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: '#8A93A3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formatKeepActiveBoxActive: {
    backgroundColor: colors.blue,
    borderColor: colors.blue,
  },
  formatKeepActiveText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  formatKeepActiveTextActive: {
    color: colors.blue,
  },
  surveyModuleEmptyPill: {
    height: 30,
    minWidth: 116,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#3F4652',
    backgroundColor: '#2A2D34',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  surveyModuleEmptyText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  regionFormatButton: {
    height: 30,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#3F4652',
    backgroundColor: '#2A2D34',
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  regionFormatButtonPrimary: {
    borderColor: colors.blue,
    backgroundColor: colors.blue,
  },
  regionFormatButtonText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  regionFormatButtonTextPrimary: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  regionConfirmText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
    maxWidth: 146,
  },
  textFormatSubToolbar: {
    position: 'absolute',
    top: 36,
    left: 0,
    right: 0,
    height: 36,
    backgroundColor: '#1B1C21',
    borderBottomWidth: 1,
    borderBottomColor: '#090A0D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 8,
    zIndex: 1,
  },
  contextColorSwatch: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  checkerCellOne: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 12,
    height: 12,
    backgroundColor: '#CFCFCF',
  },
  checkerCellTwo: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 12,
    height: 12,
    backgroundColor: '#CFCFCF',
  },
  contextColorFill: {
    ...StyleSheet.absoluteFill, // RN 0.86 removed absoluteFillObject; absoluteFill is the same object
    borderRadius: 12,
  },
  counterSwatchText: {
    position: 'relative',
    zIndex: 2,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 13,
  },
  desktopNumberInput: {
    width: 36,
    height: 24,
    paddingVertical: 0,
    paddingHorizontal: 4,
    backgroundColor: '#444',
    color: '#DDD',
    borderRadius: 5,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  desktopMenuButton: {
    height: 24,
    paddingLeft: 8,
    paddingRight: 7,
    borderRadius: 5,
    backgroundColor: '#444',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  desktopMenuButtonText: {
    flexShrink: 1,
    color: '#DDD',
    fontSize: 12,
    fontWeight: '700',
  },
  formatDropdownAnchor: {
    position: 'relative',
    zIndex: 320,
  },
  formatDropdownMenu: {
    position: 'absolute',
    top: 30,
    left: 0,
    maxHeight: 166,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#333',
    backgroundColor: '#1E1E1E',
    padding: 4,
    zIndex: 340,
  },
  formatDropdownScroll: {
    maxHeight: 156,
  },
  formatDropdownRow: {
    minHeight: 30,
    borderRadius: 4,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  formatDropdownRowActive: {
    backgroundColor: '#132135',
  },
  formatDropdownText: {
    flex: 1,
    color: '#DDD',
    fontSize: 12,
    fontWeight: '700',
  },
  formatDropdownTextActive: {
    color: colors.blue,
  },
  textFormatMenuAnchor: {
    position: 'relative',
  },
  textFormatMenuButton: {
    minWidth: 42,
    justifyContent: 'center',
  },
  textFormatDropdown: {
    position: 'absolute',
    top: 30,
    left: 0,
    minWidth: 144,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#333',
    backgroundColor: '#1E1E1E',
    padding: 4,
    zIndex: 200,
  },
  textFormatDropdownRow: {
    height: 30,
    borderRadius: 4,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  textFormatDropdownRowActive: {
    backgroundColor: 'rgba(216,168,78,0.12)',
  },
  textFormatDropdownLabel: {
    color: '#DDD',
    fontSize: 12,
    fontWeight: '700',
  },
  counterSeriesMenuAnchor: {
    position: 'relative',
    zIndex: 260,
  },
  counterSeriesDropdown: {
    position: 'absolute',
    top: 30,
    left: 0,
    minWidth: 160,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#333',
    backgroundColor: '#1E1E1E',
    padding: 4,
    zIndex: 260,
  },
  counterSeriesHeader: {
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    color: '#888',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  counterSeriesSubheader: {
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 4,
    color: '#888',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  counterSeriesRow: {
    minHeight: 30,
    borderRadius: 4,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  counterSeriesRowActive: {
    backgroundColor: '#2A2A2A',
  },
  counterSeriesDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  counterSeriesLabel: {
    flex: 1,
    color: '#DDD',
    fontSize: 12,
    fontWeight: '700',
  },
  counterSeriesCount: {
    color: '#888',
    fontSize: 10,
    fontWeight: '800',
  },
  formatPillText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '900',
  },
  formatTextModeButton: {
    minWidth: 34,
    height: 24,
    borderRadius: 5,
    backgroundColor: '#444',
    borderWidth: 1,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  formatTextModeButtonActive: {
    borderColor: colors.blue,
    backgroundColor: '#132135',
  },
  bumpControl: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  bumpLabel: {
    color: '#BBB',
    fontSize: 11,
    fontWeight: '700',
  },
  desktopFormatButton: {
    width: 28,
    height: 24,
    borderRadius: 5,
    backgroundColor: '#444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  desktopFormatButtonActive: {
    backgroundColor: 'rgba(216,168,78,0.18)',
  },
  desktopFormatButtonText: {
    color: '#DDD',
    fontSize: 13,
    fontWeight: '800',
  },
  desktopFormatButtonTextActive: {
    color: '#D8A84E',
  },
  boldFormatText: {
    fontWeight: '900',
  },
  italicFormatText: {
    fontStyle: 'italic',
  },
  underlineFormatText: {
    textDecorationLine: 'underline',
  },
  strikeFormatText: {
    textDecorationLine: 'line-through',
  },
  alignGridButton: {
    width: 28,
    height: 26,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#383D46',
    backgroundColor: '#2A2E36',
    padding: 5,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  alignGridDot: {
    width: 4,
    height: 4,
    borderRadius: 1,
    backgroundColor: 'rgba(168,176,191,0.4)',
  },
  alignGridDotActive: {
    backgroundColor: '#D8A84E',
  },
  workArea: {
    flex: 1,
    flexDirection: 'row',
  },
  rail: {
    backgroundColor: colors.rail,
    borderRightWidth: 1,
    borderRightColor: colors.line,
    paddingTop: 7,
    paddingHorizontal: 4,
    alignItems: 'center',
    gap: 5,
  },
  railButton: {
    width: 34,
    height: 34,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  railButtonActive: {
    backgroundColor: '#111820',
    borderColor: '#2B6FB6',
  },
  railDivider: {
    width: 26,
    height: 1,
    backgroundColor: '#4A4F59',
    marginVertical: 3,
  },
  railSubDivider: {
    width: 20,
    height: 1,
    backgroundColor: '#3C424C',
    marginTop: 3,
    marginBottom: 1,
  },
  railSubMiniDivider: {
    width: 18,
    height: 1,
    backgroundColor: '#3C424C',
    marginVertical: 2,
  },
  railSubToolbar: {
    width: 34,
    borderRadius: 8,
    backgroundColor: '#1A1E25',
    borderWidth: 1,
    borderColor: '#323844',
    paddingVertical: 4,
    alignItems: 'center',
    gap: 4,
  },
  railSubButton: {
    width: 28,
    height: 28,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  railSubButtonActive: {
    backgroundColor: '#111820',
    borderColor: '#2B6FB6',
  },
  railSurveyCategoryToolbar: {
    width: 34,
    borderRadius: 8,
    backgroundColor: '#1A1E25',
    borderWidth: 1,
    borderColor: '#323844',
    paddingVertical: 4,
    alignItems: 'center',
    gap: 4,
  },
  railSurveyCategoryButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#2A2D34',
    borderWidth: 1,
    borderColor: '#555C68',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  railSurveyCategoryButtonActive: {
    backgroundColor: colors.blue,
    borderColor: colors.blue,
  },
  railSurveyCategoryText: {
    color: colors.text,
    fontSize: 10,
    fontWeight: '900',
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  railSurveyCategoryTextActive: {
    color: '#FFFFFF',
  },
  railSurveyEntityToolbar: {
    width: 34,
    borderRadius: 8,
    backgroundColor: '#1A1E25',
    borderWidth: 1,
    borderColor: '#323844',
    paddingVertical: 4,
    alignItems: 'center',
    gap: 4,
  },
  railSurveyEntityButton: {
    width: 28,
    height: 24,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  railSurveyEntityButtonActive: {
    backgroundColor: '#111820',
    borderColor: colors.blue,
  },
  railSurveyEntitySwatch: {
    width: 15,
    height: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#0C0F13',
  },
  railSpacer: {
    flex: 1,
  },
  railFooterTools: {
    width: 34,
    alignItems: 'center',
    gap: 0,
    paddingBottom: 0,
    transform: [{ translateY: 34 }],
  },
  railFooterMenuButton: {
    width: 34,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  railFooterButtonStack: {
    marginTop: 4,
    alignItems: 'center',
    gap: 5,
    transform: [{ translateY: -5 }],
  },
  railFooterButton: {
    width: 34,
    height: 34,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
    position: 'relative',
    transform: [{ translateY: -3 }],
  },
  syncStatusButton: {
    width: 34,
    height: 34,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  syncStatusCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  activeUsersButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    transform: [{ translateY: -3 }],
  },
  userAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#2A3B54',
    borderWidth: 1,
    borderColor: '#4A90E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatarText: {
    color: colors.text,
    fontSize: 10,
    fontWeight: '900',
  },
  userCountBadge: {
    position: 'absolute',
    right: -2,
    top: -2,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.blue,
    borderWidth: 1,
    borderColor: colors.rail,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  userCountText: {
    color: '#FFF',
    fontSize: 9,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  documentScroll: {
    flex: 1,
    backgroundColor: '#070A0D',
  },
  documentContent: {
    paddingBottom: 88,
  },
  page: {
    backgroundColor: colors.page,
    borderWidth: 1,
    borderColor: '#D8D8D0',
    overflow: 'hidden',
  },
  planWall: {
    position: 'absolute',
    borderRadius: 2,
  },
  roomLabel: {
    position: 'absolute',
    color: '#68707A',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0,
  },
  regionOverlay: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: colors.blue,
    backgroundColor: 'rgba(74, 144, 226, 0.13)',
  },
  regionOverlayEditing: {
    borderStyle: 'dashed',
    backgroundColor: 'rgba(74, 144, 226, 0.2)',
  },
  regionOverlayText: {
    color: colors.blue,
    fontSize: 11,
    fontWeight: '800',
    padding: 4,
  },
  contextMenuDismissLayer: {
    ...StyleSheet.absoluteFill, // RN 0.86 removed absoluteFillObject; absoluteFill is the same object
    zIndex: 84,
    backgroundColor: 'rgba(0,0,0,0.01)',
  },
  contextMenuPanel: {
    position: 'absolute',
    width: 154,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#3C424D',
    backgroundColor: '#181B20',
    padding: 6,
    zIndex: 85,
    gap: 3,
  },
  contextMenuTitle: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  contextMenuDivider: {
    height: 1,
    backgroundColor: '#343A45',
  },
  contextMenuAction: {
    height: 34,
    borderRadius: 6,
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  contextMenuActionDisabled: {
    opacity: 0.45,
  },
  contextMenuActionText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  contextMenuActionTextDestructive: {
    color: '#F08A8A',
  },
  contextMenuActionTextDisabled: {
    color: colors.faint,
  },
  marker: {
    position: 'absolute',
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inkDot: {
    position: 'absolute',
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.red,
  },
  markerText: {
    color: '#111',
    fontSize: 12,
    fontWeight: '900',
  },
  bottomActionBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 45,
  },
  bottomBarSurface: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.chrome,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  bottomActionNudge: {
    transform: [{ translateY: 4 }],
  },
  bottomSideButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#181A1F',
    borderWidth: 1,
    borderColor: '#2E333C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomSideButtonActive: {
    backgroundColor: '#162236',
    borderColor: '#315F91',
  },
  bottomHubButton: {
    minWidth: 124,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#20242C',
    borderWidth: 1,
    borderColor: '#3A4250',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
  },
  bottomHubButtonActive: {
    backgroundColor: '#162236',
    borderColor: '#315F91',
  },
  bottomHubText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
    maxWidth: 82,
  },
  bottomHubTextActive: {
    color: colors.blue,
  },
  hubTray: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    backgroundColor: colors.panel,
    borderTopWidth: 1,
    borderTopColor: '#444B57',
    paddingHorizontal: 16,
    paddingTop: 10,
    gap: 8,
    zIndex: 60,
  },
  hubGrabber: {
    alignSelf: 'center',
    width: 34,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#6D7380',
    marginBottom: 2,
  },
  hubTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    position: 'relative',
  },
  hubTab: {
    width: 34,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubTabActive: {
    backgroundColor: '#1A3328',
  },
  hubClose: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#353A43',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageCounterRow: {
    height: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  pageCounterPill: {
    minWidth: 58,
    height: 30,
    paddingHorizontal: 16,
    borderRadius: 15,
    backgroundColor: '#171A20',
    borderWidth: 1,
    borderColor: '#353B46',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageCounterValue: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  pageCounterMeta: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  pageThumbScroller: {
    flexGrow: 0,
  },
  pageThumbTrack: {
    gap: 16,
    paddingHorizontal: 1,
    paddingTop: 2,
    paddingBottom: 2,
  },
  pageCard: {
    width: 130,
    height: 146,
    borderRadius: 8,
    backgroundColor: '#20242B',
    borderWidth: 1,
    borderColor: '#2F3641',
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  pageCardPressArea: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 12,
  },
  pageCardActive: {
    backgroundColor: '#1D2740',
    borderColor: '#2F6BB8',
  },
  pageCardDragging: {
    borderColor: colors.green,
    backgroundColor: '#1A2D25',
  },
  pagePreviewPaper: {
    width: 92,
    height: 112,
    borderRadius: 5,
    backgroundColor: '#FAFAF8',
    borderWidth: 1,
    borderColor: '#E5E5DE',
    overflow: 'hidden',
  },
  pagePreviewHeader: {
    height: 24,
    borderRadius: 3,
    backgroundColor: '#E7EDF4',
    marginBottom: 5,
  },
  pagePreviewLineShort: {
    width: '52%',
    height: 5,
    borderRadius: 3,
    backgroundColor: '#B9C0CA',
  },
  pagePreviewLine: {
    width: '76%',
    height: 5,
    borderRadius: 3,
    backgroundColor: '#D3D8DF',
  },
  pageCardBadge: {
    position: 'absolute',
    right: 8,
    top: 8,
    minWidth: 22,
    height: 22,
    paddingHorizontal: 7,
    borderRadius: 11,
    backgroundColor: colors.page,
    borderWidth: 1,
    borderColor: '#E1E1DA',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  pageCardBadgeText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  pageActiveRail: {
    position: 'absolute',
    left: 4,
    top: 40,
    bottom: 40,
    width: 5,
    borderRadius: 3,
    backgroundColor: '#58D976',
  },
  pageCardMore: {
    position: 'absolute',
    right: 7,
    bottom: 54,
    width: 26,
    height: 28,
    borderRadius: 7,
    backgroundColor: 'rgba(20, 24, 30, 0.82)',
    borderWidth: 1,
    borderColor: '#343A45',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageClipboardBadge: {
    position: 'absolute',
    left: 8,
    top: 8,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#132A20',
    borderWidth: 1,
    borderColor: '#2E8F5A',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  pageDragHandle: {
    position: 'absolute',
    left: 44,
    right: 44,
    bottom: 2,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageMoveButtons: {
    position: 'absolute',
    left: 6,
    right: 6,
    bottom: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  pageMoveButton: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: '#242A33',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubActionPill: {
    alignSelf: 'center',
    height: 42,
    borderRadius: 21,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  hubActionButton: {
    height: 34,
    minWidth: 72,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 9,
  },
  hubActionText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  hubActionDivider: {
    width: 1,
    height: 18,
    backgroundColor: '#343A45',
  },
  searchBox: {
    height: 42,
    borderRadius: 7,
    backgroundColor: '#171A20',
    borderWidth: 1,
    borderColor: '#333944',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 11,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    padding: 0,
  },
  resultList: {
    maxHeight: 112,
  },
  resultRow: {
    minHeight: 44,
    borderRadius: 6,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#333944',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 7,
  },
  resultTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  resultMeta: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  searchEmptyState: {
    flex: 1,
    minHeight: 160,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 9,
  },
  searchEmptyTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  searchEmptyMeta: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 17,
  },
  bookmarkList: {
    gap: 8,
  },
  bookmarkRows: {
    maxHeight: 166,
  },
  bookmarkRowsContent: {
    gap: 7,
    paddingBottom: 2,
  },
  bookmarkItem: {
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#333944',
    borderRadius: 6,
    paddingLeft: 5,
    paddingRight: 7,
    paddingVertical: 6,
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  bookmarkDragHandle: {
    width: 24,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookmarkIconBubble: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#20242C',
    borderWidth: 1,
    borderColor: '#343A45',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookmarkOpenArea: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  bookmarkCopy: {
    flex: 1,
    minWidth: 0,
  },
  bookmarkMoveButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  bookmarkMoveButton: {
    width: 22,
    height: 24,
    borderRadius: 5,
    backgroundColor: '#242A33',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookmarkMoveButtonDisabled: {
    opacity: 0.36,
  },
  bookmarkTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  bookmarkEmpty: {
    minHeight: 76,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#333944',
    backgroundColor: '#1B1F25',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  bookmarkEmptyText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  drawer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.panel,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderTopWidth: 1,
    borderTopColor: '#444B57',
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 12,
    zIndex: 65,
  },
  annotationEditSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.panel,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderTopWidth: 1,
    borderTopColor: '#444B57',
    paddingHorizontal: 16,
    paddingTop: 10,
    zIndex: 68,
  },
  annotationEditTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
  },
  annotationEditSegmentedTabs: {
    width: 224,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#1B1F25',
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  annotationEditSegmentedTab: {
    flex: 1,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  annotationEditSegmentedTabActive: {
    backgroundColor: '#132135',
  },
  annotationEditSegmentedDivider: {
    width: 1,
    height: 20,
    backgroundColor: '#343A45',
  },
  annotationEditTab: {
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#1B1F25',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 11,
  },
  annotationEditTabActive: {
    backgroundColor: '#132135',
    borderColor: '#2B6FB6',
  },
  annotationEditTabSwatch: {
    width: 11,
    height: 11,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  annotationEditTabText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  annotationEditTabTextActive: {
    color: colors.text,
  },
  annotationColorTabs: {
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#141820',
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  annotationColorTab: {
    flex: 1,
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  annotationColorTabActive: {
    backgroundColor: '#132135',
  },
  annotationColorTabsDivider: {
    width: 1,
    height: 20,
    backgroundColor: '#343A45',
  },
  annotationColorTabText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  annotationColorTabTextActive: {
    color: colors.text,
  },
  annotationEditScroll: {
    flex: 1,
    marginTop: 12,
  },
  annotationEditContent: {
    gap: 10,
  },
  annotationEditCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#1B1F25',
    padding: 11,
    gap: 10,
  },
  annotationEditCardCompact: {
    padding: 9,
    gap: 8,
  },
  annotationTextControlsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  annotationTextFormatCard: {
    flex: 1,
  },
  annotationTextSizeCard: {
    flex: 1,
    alignItems: 'center',
  },
  annotationSplitControlCard: {
    flexDirection: 'row',
    alignItems: 'stretch',
    padding: 0,
    gap: 0,
  },
  annotationSplitControlPane: {
    flex: 1,
    padding: 11,
    gap: 10,
    alignItems: 'center',
  },
  annotationSplitControlDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: '#343A45',
  },
  annotationStrokeSizeCard: {
    flex: 1,
    alignItems: 'center',
  },
  annotationStrokeStyleCard: {
    flex: 1,
    alignItems: 'center',
  },
  annotationEditCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  annotationEditLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  annotationEditValue: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
  },
  annotationEditSwatchButton: {
    borderRadius: 22,
  },
  annotationEditLargeSwatch: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
  },
  annotationEditCompactSwatch: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  annotationColorGrid: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
    gap: 0,
  },
  annotationColorChoice: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#3B424E',
    backgroundColor: '#15181D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  annotationColorChoiceActive: {
    borderColor: colors.blue,
    backgroundColor: '#122238',
  },
  annotationColorDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  gradientPickerContent: {
    gap: 12,
  },
  gradientPickerSquare: {
    height: 176,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#111318',
    position: 'relative',
  },
  gradientPickerThumb: {
    position: 'absolute',
    width: 20,
    height: 20,
    marginLeft: -10,
    marginTop: -10,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  gradientPickerRow: {
    height: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  gradientPickerLabel: {
    width: 66,
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  gradientHueTrack: {
    flex: 1,
    height: 16,
    borderRadius: 8,
    overflow: 'visible',
    position: 'relative',
    backgroundColor: '#222833',
  },
  gradientHueThumb: {
    position: 'absolute',
    top: -3,
    width: 22,
    height: 22,
    marginLeft: -11,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  gradientPickerValue: {
    width: 46,
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
  gradientOpacityTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#444B57',
    position: 'relative',
  },
  gradientOpacityFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 3,
    backgroundColor: colors.blue,
  },
  gradientOpacityThumb: {
    position: 'absolute',
    top: -12,
    width: 30,
    height: 30,
    marginLeft: -15,
    borderRadius: 15,
    backgroundColor: colors.blue,
  },
  gradientPickerDivider: {
    height: 1,
    backgroundColor: '#343A45',
  },
  gradientPickerInputRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  gradientPickerPreview: {
    width: 52,
    height: 42,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#555D6B',
  },
  gradientPickerHexInput: {
    flex: 1,
    height: 42,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#15181D',
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    paddingHorizontal: 14,
    fontVariant: ['tabular-nums'],
  },
  gradientPickerOpacityInput: {
    width: 86,
    height: 42,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#15181D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 8,
  },
  gradientPickerOpacityTextInput: {
    flex: 1,
    color: colors.text,
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'right',
    padding: 0,
    fontVariant: ['tabular-nums'],
  },
  gradientPickerPercentText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '900',
  },
  gradientPickerDoneButton: {
    height: 42,
    borderRadius: 8,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gradientPickerDoneText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  annotationEditRow: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  annotationEditRowTight: {
    height: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  annotationEditNumberInput: {
    width: 52,
    height: 32,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#3A4250',
    backgroundColor: '#242A33',
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
    padding: 0,
    fontVariant: ['tabular-nums'],
  },
  annotationDropdownField: {
    minHeight: 36,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#3A4250',
    backgroundColor: '#242A33',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  annotationDropdownValue: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  annotationDropdownWrap: {
    position: 'relative',
    zIndex: 30,
  },
  annotationDropdownFullWidth: {
    alignSelf: 'stretch',
  },
  annotationDropdownMenu: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#171A20',
    padding: 4,
    gap: 2,
  },
  annotationDropdownMenuPopover: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 42,
    maxHeight: 174,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#171A20',
    padding: 4,
    zIndex: 80,
  },
  annotationDropdownMenuScroll: {
    maxHeight: 164,
  },
  annotationDropdownItem: {
    minHeight: 34,
    borderRadius: 6,
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  annotationDropdownItemActive: {
    backgroundColor: '#132135',
  },
  annotationDropdownItemText: {
    flex: 1,
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  annotationDropdownItemTextActive: {
    color: colors.text,
  },
  annotationChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  annotationChip: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#242A33',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  annotationChipActive: {
    borderColor: '#2B6FB6',
    backgroundColor: '#132135',
  },
  annotationChipText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  annotationChipTextActive: {
    color: colors.text,
  },
  annotationFormatToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 5,
  },
  annotationFormatToggle: {
    width: 31,
    height: 31,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#242A33',
    alignItems: 'center',
    justifyContent: 'center',
  },
  annotationAlignmentGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  annotationAlignmentGroupLabel: {
    width: 72,
    color: colors.muted,
    fontSize: 10,
    fontWeight: '900',
  },
  annotationAlignmentChoiceRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 5,
  },
  annotationAlignmentChoice: {
    flex: 1,
    height: 43,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#242A33',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 3,
  },
  annotationAlignmentChoiceActive: {
    borderColor: '#2B6FB6',
    backgroundColor: '#132135',
  },
  annotationAlignButton: {
    width: 34,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#242A33',
    padding: 7,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  drawerTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  drawerSubtitle: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
  },
  versionList: {
    flex: 1,
  },
  versionListContent: {
    gap: 7,
    paddingBottom: 2,
  },
  versionRow: {
    minHeight: 50,
    borderRadius: 8,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  versionDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#58D976',
  },
  versionCopy: {
    flex: 1,
  },
  versionTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  versionMeta: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
  },
  activeUserRow: {
    minHeight: 54,
    borderRadius: 8,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  activeUserAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#2A3B54',
    borderWidth: 1,
    borderColor: '#4A90E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeUserAvatarOwner: {
    backgroundColor: '#263A2D',
    borderColor: '#58D976',
  },
  activeUserAvatarText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '900',
  },
  activeUserStatusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#58D976',
  },
  spaceCard: {
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    borderRadius: 8,
    padding: 10,
    gap: 10,
  },
  spaceTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  spaceName: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  spaceMeta: {
    color: colors.muted,
    fontSize: 11,
  },
  regionCard: {
    backgroundColor: '#242A33',
    borderRadius: 6,
    padding: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  regionName: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  regionMeta: {
    color: colors.muted,
    fontSize: 10,
    marginTop: 3,
  },
  toggle: {
    width: 40,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#3A3F49',
    padding: 3,
  },
  toggleActive: {
    backgroundColor: '#28598D',
  },
  toggleKnob: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.muted,
  },
  toggleKnobActive: {
    transform: [{ translateX: 16 }],
    backgroundColor: colors.text,
  },
  editRegionButton: {
    height: 34,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#315F91',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  editRegionText: {
    color: colors.blue,
    fontSize: 12,
    fontWeight: '800',
  },
  newSpaceButton: {
    flex: 1,
    height: 38,
    borderRadius: 6,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newSpaceText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '800',
  },
  drawerFooter: {
    flexDirection: 'row',
    gap: 10,
  },
  exitRegionButton: {
    flex: 1,
    height: 38,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#3A4250',
    backgroundColor: '#1B1F25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exitRegionText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  spacesDrawer: {
    gap: 9,
    paddingTop: 10,
  },
  spacesDrawerHeader: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  spacesHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  spacesHeaderButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#1B1F25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spacesHeaderButtonActive: {
    borderColor: '#2B6FB6',
    backgroundColor: '#132135',
  },
  spacesHeaderButtonDisabled: {
    opacity: 0.45,
  },
  spacesExportWrap: {
    position: 'relative',
    zIndex: 30,
  },
  spacesExportMenu: {
    position: 'absolute',
    right: 0,
    top: 36,
    width: 116,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#3C424D',
    backgroundColor: '#181B20',
    padding: 5,
    gap: 4,
  },
  spacesExportMenuItem: {
    height: 30,
    borderRadius: 5,
    paddingHorizontal: 9,
    justifyContent: 'center',
  },
  spacesExportMenuText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  spacesList: {
    flex: 1,
  },
  spacesListContent: {
    gap: 8,
    paddingBottom: 2,
  },
  spaceCardActive: {
    borderColor: 'transparent',
    backgroundColor: '#2B2B2B',
  },
  spaceCardHeader: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  spaceCardLeadingControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  spaceDragHandle: {
    width: 20,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spaceRegionCountBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#1F1F1F',
    borderWidth: 1,
    borderColor: '#3A3A3A',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  spaceRegionCountText: {
    color: colors.text,
    fontSize: 10,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  spaceExpandButton: {
    width: 22,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spaceNameInput: {
    flex: 1,
    minWidth: 0,
    height: 30,
    color: colors.text,
    fontSize: 14,
    fontWeight: '900',
    padding: 0,
  },
  spaceHeaderControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  spaceDeleteButton: {
    width: 25,
    height: 25,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  spaceCollapsedMetaRow: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingLeft: 52,
  },
  rowMoveButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  spaceExpandedBody: {
    borderTopWidth: 1,
    borderTopColor: '#3A3A3A',
    paddingTop: 9,
    gap: 8,
  },
  spacePageAssignRow: {
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  spacePageInput: {
    flex: 1,
    height: 28,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#1F1F1F',
    color: colors.text,
    fontSize: 11,
    fontWeight: '800',
    paddingHorizontal: 8,
    paddingVertical: 0,
  },
  spaceAddPagesButton: {
    width: 28,
    height: 28,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#3A3A3A',
    backgroundColor: '#242A33',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spaceSmallButtonText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '800',
  },
  spaceIconButton: {
    width: 32,
    height: 32,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#242A33',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spacePageError: {
    color: '#F08A8A',
    fontSize: 11,
    fontWeight: '800',
  },
  spacePageRows: {
    gap: 6,
  },
  spaceNoPagesRow: {
    minHeight: 34,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#333333',
    backgroundColor: '#1F1F1F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spaceExpandedFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 4,
  },
  spacePageRow: {
    minHeight: 38,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#333333',
    backgroundColor: '#1F1F1F',
    paddingHorizontal: 7,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  spacePageRowActive: {
    borderColor: '#2B6FB6',
    backgroundColor: '#17263A',
  },
  spacePageRowEditing: {
    borderStyle: 'dashed',
  },
  spacePageLeadingControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  spacePagePill: {
    minWidth: 26,
    height: 24,
    borderRadius: 5,
    backgroundColor: '#242A33',
    borderWidth: 1,
    borderColor: '#3A3A3A',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  spacePagePillText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  regionOverlayToggle: {
    width: 28,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#3A3A3A',
    borderWidth: 1,
    borderColor: '#4A4A4A',
    padding: 2,
  },
  regionOverlayToggleDisabled: {
    opacity: 0.45,
  },
  regionOverlayToggleKnob: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.muted,
  },
  regionOverlayToggleKnobActive: {
    transform: [{ translateX: 12 }],
    backgroundColor: colors.text,
  },
  spacePageCopy: {
    flex: 1,
    minWidth: 0,
  },
  spacePageRegionName: {
    height: 19,
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
    padding: 0,
  },
  regionActionControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  regionCardActive: {
    borderWidth: 1,
    borderColor: '#2B6FB6',
    backgroundColor: '#17263A',
  },
  regionCardEditing: {
    borderStyle: 'dashed',
  },
  regionDragHandle: {
    width: 18,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  regionCopy: {
    flex: 1,
    minWidth: 0,
  },
  regionNameInput: {
    height: 22,
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
    padding: 0,
  },
  regionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  regionActionButton: {
    width: 26,
    height: 26,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#1B1F25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  regionActionButtonActive: {
    borderColor: '#2B6FB6',
    backgroundColor: '#132135',
  },
  regionActionButtonDisabled: {
    opacity: 0.45,
  },
  regionToggle: {
    width: 34,
    height: 21,
    borderRadius: 11,
    backgroundColor: '#3A3F49',
    padding: 3,
  },
  regionToggleKnob: {
    width: 15,
    height: 15,
    borderRadius: 8,
    backgroundColor: colors.muted,
  },
  regionToggleKnobActive: {
    transform: [{ translateX: 13 }],
    backgroundColor: colors.text,
  },
  regionMoveDeleteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  regionTinyButton: {
    width: 22,
    height: 24,
    borderRadius: 5,
    backgroundColor: '#1B1F25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyRegionRow: {
    minHeight: 34,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#15181D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spaceEmptyState: {
    minHeight: 92,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#1B1F25',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  spaceEmptyText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  exitRegionButtonFull: {
    height: 36,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#51404A',
    backgroundColor: '#1B1F25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.panel,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderTopWidth: 1,
    borderTopColor: '#444B57',
    paddingHorizontal: 16,
    paddingTop: 6,
    zIndex: 70,
  },
  dismissLayer: {
    ...StyleSheet.absoluteFill, // RN 0.86 removed absoluteFillObject; absoluteFill is the same object
    backgroundColor: 'rgba(0,0,0,0.01)',
    zIndex: 25,
  },
  popoverDismissLayer: {
    zIndex: 65,
  },
  sheetFixedTop: {
    flexShrink: 0,
    zIndex: 10,
  },
  sheetFixedBody: {
    flexShrink: 0,
    zIndex: 8,
  },
  sheetFooter: {
    flexShrink: 0,
    height: 38,
    paddingTop: 6,
  },
  exitSurveyButton: {
    height: 32,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#51404A',
    backgroundColor: '#1B1F25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exitSurveyText: {
    color: '#F08A8A',
    fontSize: 13,
    fontWeight: '900',
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#68707A',
    marginBottom: 7,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetTitleColumn: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 45,
  },
  sheetHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    position: 'relative',
    zIndex: 40,
  },
  sheetEyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  sheetTitle: {
    color: colors.text,
    flexShrink: 1,
    fontSize: 17,
    fontWeight: '900',
  },
  templateTitleButton: {
    height: 25,
    marginTop: 1,
    paddingRight: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    alignSelf: 'flex-start',
    maxWidth: '96%',
  },
  templateDropdownMenu: {
    position: 'absolute',
    top: 43,
    left: 0,
    width: 236,
    backgroundColor: '#181B20',
    borderWidth: 1,
    borderColor: '#3C424D',
    borderRadius: 8,
    padding: 5,
    gap: 4,
    zIndex: 100,
  },
  templatePickerBody: {
    paddingTop: 10,
    gap: 8,
  },
  templatePickerList: {
    gap: 7,
  },
  templatePickerItem: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#1B1F25',
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  templatePickerIcon: {
    width: 26,
    height: 26,
    borderRadius: 6,
    backgroundColor: '#132235',
    borderWidth: 1,
    borderColor: '#294A72',
    alignItems: 'center',
    justifyContent: 'center',
  },
  templatePickerCopy: {
    flex: 1,
    minWidth: 0,
  },
  templatePickerTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  templatePickerMeta: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
  },
  exportButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#353A43',
    borderWidth: 1,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exportButtonActive: {
    backgroundColor: '#162236',
    borderColor: '#315F91',
  },
  exportMenu: {
    position: 'absolute',
    right: 0,
    top: 42,
    width: 218,
    borderRadius: 8,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    padding: 6,
    gap: 5,
    zIndex: 60,
  },
  exportMenuItem: {
    minHeight: 48,
    borderRadius: 6,
    paddingHorizontal: 9,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  exportMenuTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  exportMenuMeta: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
  },
  sheetRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  moduleNavigator: {
    flex: 1,
    height: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  moduleArrow: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    alignItems: 'center',
    justifyContent: 'center',
  },
  moduleArrowDisabled: {
    opacity: 0.45,
  },
  moduleDropdownWrap: {
    flex: 1,
    position: 'relative',
    zIndex: 20,
  },
  moduleCenter: {
    height: 32,
    borderRadius: 16,
    backgroundColor: '#181B20',
    borderWidth: 1,
    borderColor: '#343A45',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
  },
  moduleCenterText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  moduleSwitch: {
    flex: 1,
    height: 36,
    borderRadius: 7,
    backgroundColor: '#181B20',
    padding: 3,
    flexDirection: 'row',
  },
  moduleOption: {
    flex: 1,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moduleOptionActive: {
    backgroundColor: '#303847',
  },
  moduleText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  moduleTextActive: {
    color: colors.text,
  },
  progressPill: {
    height: 34,
    minWidth: 52,
    borderRadius: 17,
    backgroundColor: '#1C3325',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressText: {
    color: '#A7F0B8',
    fontWeight: '900',
    fontSize: 12,
    fontVariant: ['tabular-nums'],
  },
  fieldLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 13,
    textTransform: 'uppercase',
  },
  compactFieldLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '800',
    marginTop: 7,
    textTransform: 'uppercase',
  },
  markerNameInput: {
    flex: 1,
    minWidth: 0,
    height: 30,
    borderRadius: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
    color: colors.text,
    paddingHorizontal: 10,
    paddingVertical: 0,
    fontSize: 13,
    fontWeight: '900',
  },
  markerToolsWrap: {
    position: 'relative',
    zIndex: 12,
  },
  markerToolsRow: {
    marginTop: 4,
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  markerItemFieldWrap: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
    zIndex: 20,
  },
  markerItemInputRow: {
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 7,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
  },
  markerItemDropdownButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: '#343A45',
  },
  markerItemMenu: {
    position: 'absolute',
    top: 36,
    left: 0,
    right: 0,
    backgroundColor: '#181B20',
    borderWidth: 1,
    borderColor: '#3C424D',
    borderRadius: 8,
    padding: 5,
    gap: 4,
    zIndex: 95,
  },
  markerEntitySwatchButton: {
    width: 30,
    height: 30,
    borderRadius: 7,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerEntitySwatchEmpty: {
    borderColor: '#4A5361',
    backgroundColor: '#20242C',
  },
  markerEntitySwatch: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#D7DEE8',
  },
  locateMarkerButton: {
    width: 30,
    height: 30,
    borderRadius: 7,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerNotesIconButton: {
    width: 30,
    height: 30,
    borderRadius: 7,
    backgroundColor: 'transparent',
    borderWidth: 0,
    opacity: 0.78,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerEntityMenu: {
    position: 'absolute',
    top: 36,
    left: 0,
    width: 230,
    backgroundColor: '#181B20',
    borderWidth: 1,
    borderColor: '#3C424D',
    borderRadius: 8,
    padding: 5,
    gap: 4,
    zIndex: 90,
  },
  dropdownWrap: {
    position: 'relative',
    zIndex: 12,
  },
  dropdownWrapActive: {
    zIndex: 40,
  },
  dropdownField: {
    height: 38,
    marginTop: 7,
    borderRadius: 7,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  compactDropdownField: {
    height: 30,
    marginTop: 4,
    borderRadius: 7,
    backgroundColor: '#1B1F25',
    borderWidth: 1,
    borderColor: '#343A45',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  dropdownFieldEmpty: {
    borderColor: '#4A5361',
    backgroundColor: '#20242C',
  },
  dropdownValue: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  dropdownPlaceholder: {
    color: colors.muted,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 41,
    left: 0,
    right: 0,
    backgroundColor: '#181B20',
    borderWidth: 1,
    borderColor: '#3C424D',
    borderRadius: 8,
    padding: 5,
    gap: 4,
    zIndex: 90,
  },
  dropdownItem: {
    minHeight: 34,
    borderRadius: 6,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dropdownItemActive: {
    backgroundColor: '#20344D',
  },
  dropdownItemText: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  dropdownMeta: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  entityDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  checkHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  assignedText: {
    color: colors.faint,
    fontSize: 11,
  },
  surveyCategoryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingTop: 8,
    paddingBottom: 5,
  },
  surveyCategoryList: {
    flex: 1,
    minHeight: 0,
  },
  surveyCategoryListContent: {
    gap: 6,
    paddingBottom: 8,
  },
  surveyCategoryCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#1B1F25',
    overflow: 'hidden',
  },
  surveyCategoryCardActive: {
    borderColor: '#2B6FB6',
    backgroundColor: '#142236',
  },
  surveyCategoryRow: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
  },
  surveyCategoryMain: {
    flex: 1,
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 10,
  },
  surveyCategoryName: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  surveyCategoryNameActive: {
    color: colors.blue,
  },
  surveyCategoryCount: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  surveyCategoryExpand: {
    width: 36,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  surveyCategoryItems: {
    borderTopWidth: 1,
    borderTopColor: '#343A45',
    paddingVertical: 6,
    paddingHorizontal: 7,
    gap: 5,
  },
  surveyCategoryItemRow: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#171B22',
    borderWidth: 1,
    borderColor: '#303743',
  },
  surveyCategoryItemName: {
    flex: 1,
    minWidth: 0,
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  surveyCategoryEmptyItems: {
    minHeight: 30,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  surveyCategoryEmptyText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  notesEditorScroll: {
    flex: 1,
    marginTop: 10,
  },
  notesEditorContent: {
    gap: 9,
    paddingBottom: 10,
  },
  notesEditorCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#1B1F25',
    padding: 10,
    gap: 8,
  },
  notesEditorInput: {
    minHeight: 88,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#3A4250',
    backgroundColor: '#15181D',
    color: colors.text,
    paddingHorizontal: 10,
    paddingVertical: 9,
    fontSize: 13,
    fontWeight: '700',
  },
  notesEditorSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  notesUploadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    justifyContent: 'flex-end',
  },
  notesUploadButton: {
    flex: 1,
    maxWidth: 112,
    minHeight: 30,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#343A45',
    backgroundColor: '#242A33',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 9,
  },
  notesUploadText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '800',
  },
  notesEmptyText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  attachmentRow: {
    minHeight: 40,
    borderRadius: 7,
    backgroundColor: '#242A33',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 8,
  },
  attachmentThumb: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#17263A',
    borderWidth: 1,
    borderColor: '#2B6FB6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachmentName: {
    flex: 1,
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  attachmentRemoveButton: {
    width: 26,
    height: 26,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notesEditorFooter: {
    height: 44,
    flexDirection: 'row',
    gap: 10,
    paddingTop: 6,
  },
  notesCancelButton: {
    flex: 1,
    height: 36,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#3A4250',
    backgroundColor: '#1B1F25',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notesCancelText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  notesSaveButton: {
    flex: 1,
    height: 36,
    borderRadius: 7,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notesSaveText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  checkList: {
    gap: CHECKLIST_ITEM_GAP,
  },
  checkListScroll: {
    flexGrow: 0,
    flexShrink: 0,
    marginTop: 6,
    zIndex: 1,
  },
  emptyChecklist: {
    marginTop: 6,
    borderRadius: 6,
    backgroundColor: '#1C2026',
    borderWidth: 1,
    borderColor: '#333944',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyChecklistText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  checkItem: {
    height: CHECKLIST_ITEM_HEIGHT,
    borderRadius: 6,
    backgroundColor: '#1C2026',
    borderWidth: 1,
    borderColor: '#333944',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 8,
  },
  checkBox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxActive: {
    backgroundColor: colors.green,
  },
  checkText: {
    flex: 1,
    minWidth: 0,
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  checkResponseGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 0,
  },
  checkResponseButton: {
    minWidth: 28,
    height: 24,
    borderRadius: 5,
    backgroundColor: '#2A2F38',
    borderWidth: 1,
    borderColor: '#3A4250',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  checkResponseButtonActive: {
    borderColor: 'transparent',
  },
  checkResponseYes: {
    backgroundColor: '#2F7D55',
  },
  checkResponseNo: {
    backgroundColor: '#8C3A42',
  },
  checkResponseNa: {
    backgroundColor: '#5E6570',
  },
  checkResponseText: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: '900',
  },
  checkResponseTextActive: {
    color: '#FFF',
  },
});

export { styles };
